### ISSUE TITLE
Error following steps from README

### ISSUE THREAD

**Issue by danielcosta** [nanobox-quickstarts/nanobox-phalcon#2]
Hello there, I tried to run the steps from README but after all downloads, when I access http://phalcon.dev the following is rendered:

```
Notice: Undefined index: DATA_DB_HOST in /app/app/config/config.php on line 12

Notice: Undefined index: DATA_DB_USER in /app/app/config/config.php on line 13

Notice: Undefined index: DATA_DB_PASS in /app/app/config/config.php on line 14

Warning: Phalcon\Mvc\View\Engine\Volt\Compiler::compileFile(/app/cache/_app_app_views_index_index.volt.php): failed to open stream: No such file or directory in /app/public/index.php on line 37
Volt directory can't be written<br><pre>#0 [internal function]: Phalcon\Mvc\View\Engine\Volt\Compiler->compileFile('/app/app/views/...', '/app/cache/_app...', false)
#1 [internal function]: Phalcon\Mvc\View\Engine\Volt\Compiler->compile('/app/app/views/...')
#2 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/app/app/views/...', Array, true)
#3 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'index/index', true, true, NULL)
#4 [internal function]: Phalcon\Mvc\View->render('index', 'index')
#5 /app/public/index.php(37): Phalcon\Mvc\Application->handle()
#6 {main}</pre>
```

Do you have any idea on what's happening here and how could I fix this?

**Comment by danielcosta** [comment]
Nevermind, following the steps directly from [nanobox guides](https://guides.nanobox.io/php/phalcon/from-scratch/) it worked! I believe the README should link there instead of trying to reproduce steps to setup the environment...

thank you!

**Comment by sanderson** [comment]
Thanks @danielcosta, I'm actually in the process of defining a new pattern for quickstarts and the Phalcon quickstart is next on my list, so this should be updated soon. I plan on releasing a blog post with about the new proposed pattern next week with links to examples.
